host = 'https://cloud.appwrite.io/v1'
cliente = 'https://my-web-site'
project = 'id-project'
db = 'id-database'
key = 'my-key'
function_key = ''
cli_email= 'email to log in to the appwrite cli'
cli_password = 'console password'